version: "3"
services:
  front:
    image: node:lts-alpine
    working_dir: /usr/src/front
    expose:
      - ${NEXT_PORT}
    ports:
      - ${NEXT_PORT}:${NEXT_PORT}
    volumes:
      - ./front/:/usr/src/front/
      - .env:/usr/src/front/.env
    entrypoint:
      - npm
      - run
      - dev
    env_file:
      - .env

  api:
    image: node:lts-alpine
    working_dir: /usr/src/api
    expose:
      - ${NODE_PORT}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - db
    volumes:
      - ./api/:/usr/src/api/
      - .env:/usr/src/api/.env
    entrypoint:
      - npm
      - run
      - dev
    env_file:
      - .env

  db:
    image: postgres:alpine
    hostname: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/confetti-dump.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db-data/:/var/lib/postgresql/data/
    env_file:
      - .env