version: "3"
services:
  # front:
  #   image: confetti-front
  #   ports:
  #     - 8080:8080

  api:
    image: confetti-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
      - db
    volumes:
      - ./api/:/usr/src/app/
      - .env:/usr/src/app/.env
    env_file:
      - .env

  db:
    image: postgres:alpine
    hostname: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/confetti-dump.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db-data/:/var/lib/postgresql/data/
    env_file:
      - .env